services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - blackbox
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/targets/:/etc/prometheus/targets/
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    ports:
      - "127.0.0.1:9115:9115"
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"
    cap_add:
      - NET_RAW
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.example.com:587"
      GF_SMTP_USER: "grafana@example.com"
      GF_SMTP_PASSWORD: "Passwort"
      GF_SMTP_FROM_ADDRESS: "grafana@example.com"
      GF_SMTP_FROM_NAME: "Grafana"
      GF_SMTP_SKIP_VERIFY: "false"
      GF_SMTP_STARTTLS_POLICY: "MandatoryStartTLS"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
