apiVersion: 1

contactPoints:
  - origId: 1
    name: email-admin
    
    receivers:
      - uid: email
        type: email
        settings:
          addresses: "keinbsp@bsp.de"
          singleEmail: false